#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Rainbow JS CodeGeneration.
//     (https://github.com/asmagin/rainbow-js-codegeneration)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HagerDeep.Feature.Media
{
    public partial class Templates
    {
        public struct DeepVideoRenderingParameters
        {
            public const string Id = "{5AB41D25-99FE-48AB-848D-6DC8EEE23165}";
            public struct Fields
            {   
            }
        }
        public struct DeepVideo
        {
            public const string Id = "{BEB5C966-A63F-4721-9B74-174E24A5757C}";
            public struct Fields
            {   
                public const string DailymotionMovie = "{5DDDF278-5A22-470C-B6D3-A6615D30B590}";
                public const string VimeoMovie = "{BE5F9344-6831-44D0-9860-C62C1F54741A}";
            }
        }
        public struct DeepVideoFolder
        {
            public const string Id = "{870FF4C5-C01F-4EF6-8871-41C333889491}";
            public struct Fields
            {   
            }
        }
        public struct PicturesGallery
        {
            public const string Id = "{C00596A5-807B-4C0D-95AC-5089A32A1588}";
            public struct Fields
            {   
                public const string Title = "{B5AE5D85-5BB0-433E-BACE-1719B1F9CEF6}";
            }
        }
        public struct PicturesGalleryFolder
        {
            public const string Id = "{AA96088F-B4C0-4F2E-AA32-6F6C0046DB7E}";
            public struct Fields
            {   
            }
        }
        public struct PicturesGalleryGroup
        {
            public const string Id = "{ECB1BF93-0E57-47C0-B3B4-2C610D11FC5C}";
            public struct Fields
            {   
            }
        }
        public struct PicturesGalleryRenderingParameters
        {
            public const string Id = "{912E7727-F3BB-4976-B833-AC7F451D0A14}";
            public struct Fields
            {   
            }
        }
        public struct PicturesGallerySlide
        {
            public const string Id = "{23A1082D-EDD3-401B-92F0-89010C7F15C5}";
            public struct Fields
            {   
                public const string SlideImage = "{91597D0C-B5AF-48B7-B5A2-D02EF0CB2170}";
                public const string SlideText = "{E04C1F2C-041A-41F8-B8AD-F1646361751B}";
            }
        }
    }
}